# =============================================================================
# 1.   IBC Startup Settings
# =============================================================================

FIX=no

OverrideTwsApiPort=7496

# =============================================================================
# 2.   Authentication Settings
# =============================================================================

# IB API Authentication Settings

# TWS username:
IbLoginId=

# TWS password:
IbPassword=

# FIX CTCI Authentication Settings

# FIX CTCI username:
FIXLoginId=

# FIX CTCI password:
FIXPassword=

# Second Factor Authentication Settings
SecondFactorDevice=

# Trading Mode
TradingMode=live

# Paper-trading Account Warning
AcceptNonBrokerageAccountWarning=yes

# Login Dialog Display Timeout
LoginDialogDisplayTimeout=40

# =============================================================================
# 3.   TWS Startup Settings
# =============================================================================

# Store settings on server
StoreSettingsOnServer=no

# Minimize TWS on startup
MinimizeMainWindow=no

# Existing Session Detected Action
ExistingSessionDetectedAction=primary

# Read-only Login
ReadOnlyLogin=no

# API Precautions
BypassOrderPrecautions=yes
BypassBondWarning=yes
BypassNegativeYieldToWorstConfirmation=yes
BypassCalledBondWarning=yes
BypassSameActionPairTradeWarning=yes
BypassPriceBasedVolatilityRiskWarning=yes
BypassUSStocksMarketDataInSharesWarning=yes
BypassRedirectOrderWarning=yes
BypassNoOverfillProtectionPrecaution=yes

# Market data size for US stocks - lots or shares
AcceptBidAskLastSizeDisplayUpdateNotification=accept
SendMarketDataInLotsForUSstocks=no

# Reset Order ID Sequence
ResetOrderIdsAtStart=no
ConfirmOrderIdReset=confirm/reject

# =============================================================================
# 4.   TWS Auto-Logoff, Auto-Restart and Cold Restart
# =============================================================================
AutoLogoffTime=06:45 AM
AutoRestartTime=07:00 AM

# Auto-Restart limitations and Cold Restart
ColdRestartTime=08:00 AM

# =============================================================================
# 5.   TWS Tidy Closedown Time
# =============================================================================
ClosedownAt=

# =============================================================================
# 6.   Other TWS Settings
# =============================================================================

# Accept Incoming Connection
AcceptIncomingConnectionAction=accept

# Allow Blind Trading
AllowBlindTrading=yes

# Save Settings on a Schedule
SaveTwsSettingsAt=Every 2 hours 08:00 00:00

# Confirm Crypto Currency Orders Automatically
ConfirmCryptoCurrencyOrders=transmit

# =============================================================================
# 7.   Settings Specific to Indian Versions of TWS
# =============================================================================
DismissPasswordExpiryWarning=nyes
DismissNSEComplianceNotice=yes

# =============================================================================
# 8.   IBC Command Server Settings
# =============================================================================

# Command Server Port Number
#CommandServerPort=7462
CommandServerPort=0

# Permitted Command Sources
ControlFrom=

# Address for Receiving Commands
BindAddress=

# Command Prompt
# CommandPrompt=>
CommandPrompt=

# Suppress Command Server Info Messages
SuppressInfoMessages=yes

# =============================================================================
# 9.   Diagnostic Settings
# =============================================================================

# Scope of Structure Logging
LogStructureScope=known

# When to Log Window Structure
LogStructureWhen=never
